services:
  db:
    image: mariadb:10.11
    container_name: umkm_db
    restart: always
    environment:
      MARIADB_DATABASE: db_umkm
      MARIADB_ROOT_PASSWORD: root_password_change_me
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  app:
    build: .
    container_name: umkm_app
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:mariadb://db:3306/db_umkm?createDatabaseIfNotExist=true&useSSL=false
      - DB_USERNAME=root
      - DB_PASSWORD=root_password_change_me
    depends_on:
      - db
    volumes:
      - uploads_data:/uploads

volumes:
  mariadb_data:
  uploads_data:
