spring.application.name=umkm

# Default Active Profile
spring.profiles.active=local

# Server Configuration
server.port=8081

# File Upload Configuration
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
